-- ===================================================
-- 作業 9: 資料定義語言 (DDL) 與資料表管理
-- ===================================================

/* 01. 請新建 會員資料表MEMBER */
CREATE TABLE MEMBER(
	ID INT NOT NULL AUTO_INCREMENT COMMENT '編號',
	USERNAME VARCHAR(50) COMMENT '使用者名稱',
	PASSWORD VARCHAR(50) COMMENT '密碼',
	PASS BIT(1) NOT NULL DEFAULT 0 COMMENT '帳號啟用記號',
	CREATOR VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '建立者',
	CREATED_AT DATETIME NOT NULL DEFAULT NOW() COMMENT '建立日期時間',
	UPDATER VARCHAR(100) DEFAULT 'SYSTEM' COMMENT '修改者',
	LAST_UPDATED_AT DATETIME,
	SESSION_ID CHAR(32),
	PRIMARY KEY (ID)
);
SELECT * FROM MEMBER;


/* 02. 請替資料表MEMBER的欄位PASSWORD之後加入一欄位 NICKNAME */
-- 【審查修正】原作業將 NICKNAME 加在 SESSION_ID 後，不符合要求。
-- 已修正為加在 PASSWORD 之後。
ALTER TABLE MEMBER
ADD COLUMN NICKNAME VARCHAR(100) NOT NULL COMMENT '暱稱' AFTER PASSWORD;
SELECT * FROM MEMBER;

/* 03. 請修改資料表MEMBER的欄位
 * USERNAME、PASSWORD: NOT NULL、長度100
 * LAST_UPDATED_AT: 預設值NOW()、註解"最後修改日期時間"
 */
-- 【審查修正】使用 CHANGE COLUMN 或 MODIFY COLUMN。
-- CHANGE COLUMN 可以同時修改欄位名稱、資料類型和約束。
ALTER TABLE MEMBER
	CHANGE COLUMN USERNAME USERNAME VARCHAR(100) NOT NULL COMMENT '使用者名稱',
	CHANGE COLUMN PASSWORD PASSWORD VARCHAR(100) NOT NULL COMMENT '密碼',
	CHANGE COLUMN LAST_UPDATED_AT LAST_UPDATED_AT DATETIME DEFAULT NOW() COMMENT '最後修改日期時間';

SELECT * FROM MEMBER;

-- #04. 請將資料表MEMBER的欄位USERNAME設為唯一鍵
ALTER TABLE MEMBER ADD CONSTRAINT UK_MEMBER_USERNAME UNIQUE KEY (USERNAME);

-- #05. 請將資料表MEMBER的欄位USERNAME的唯一鍵約束移除
-- 【注意】在 MySQL 中，刪除 UNIQUE KEY 時，通常是刪除 KEY 名稱，而非 CONSTRAINT 名稱。
ALTER TABLE MEMBER DROP KEY UK_MEMBER_USERNAME;

-- #06. 請將資料表MEMBER的欄位SESSION_ID移除
ALTER TABLE MEMBER DROP COLUMN SESSION_ID;

-- #07. 請新建資料表 MEMBER2、MEMBER3，2個資料表的結構跟資料須與資料表MEMBER一樣
-- 使用 LIKE 可以複製結構 (不含資料)
CREATE TABLE MEMBER2 LIKE MEMBER;
CREATE TABLE MEMBER3 LIKE MEMBER;

-- #08. 請將資料表MEMBER2改名為MEMBER_HIS
ALTER TABLE MEMBER2 RENAME TO MEMBER_HIS;

-- #09. 請將資料表MEMBER3截斷(truncate)
TRUNCATE TABLE MEMBER3;

-- #10. 請將資料表MEMBER3的儲存引擎改為MyISAM
ALTER TABLE MEMBER3 ENGINE = MyISAM;

-- #11. 請將資料表MEMBER3移除
DROP TABLE MEMBER3;
